-- Core schema for auth-backed user data and AI-generated planning lifecycle.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  email text not null default '',
  initials text not null default '',
  weekly_time_budget_minutes integer not null default 240,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.skills_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_id text not null,
  xp integer not null default 0,
  max_xp integer not null default 0,
  level integer not null default 1,
  progress integer not null default 0,
  streak integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id, skill_id)
);

create table if not exists public.weekly_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_id text not null,
  difficulty text not null check (difficulty in ('facile', 'moyen', 'difficile')),
  status text not null check (status in ('draft', 'accepted', 'active', 'completed')),
  sessions_per_week integer not null,
  weekly_time text not null,
  summary text not null,
  source text not null check (source in ('ai', 'fallback')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plan_sessions (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.weekly_plans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_id text not null,
  day_index integer not null check (day_index between 0 and 6),
  title text not null,
  duration_minutes integer not null default 30,
  task_ids text[] not null default '{}',
  order_index integer not null default 0,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.session_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_session_id uuid not null references public.plan_sessions(id) on delete cascade,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null check (status in ('started', 'completed', 'abandoned')),
  gained_xp integer not null default 0
);
